In [7]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
SELECT f.name,x.month, x.Total_slot
FROM (
SELECT b.facid, strftime('%Y-%m', b.starttime) AS month, SUM(b.slots) AS Total_slot
FROM Bookings AS b
WHERE b.memid>0
GROUP BY b.facid, month) AS x
LEFT JOIN Facilities AS f ON f.facid=x.facid;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Tennis Court 1', '2012-07', 201)
('Tennis Court 1', '2012-08', 339)
('Tennis Court 1', '2012-09', 417)
('Tennis Court 2', '2012-07', 123)
('Tennis Court 2', '2012-08', 345)
('Tennis Court 2', '2012-09', 414)
('Badminton Court', '2012-07', 165)
('Badminton Court', '2012-08', 414)
('Badminton Court', '2012-09', 507)
('Table Tennis', '2012-07', 98)
('Table Tennis', '2012-08', 296)
('Table Tennis', '2012-09', 400)
('Massage Room 1', '2012-07', 166)
('Massage Room 1', '2012-08', 316)
('Massage Room 1', '2012-09', 402)
('Massage Room 2', '2012-07', 8)
('Massage Room 2', '2012-08', 18)
('Massage Room 2', '2012-09', 28)
('Squash Court', '2012-07', 50)
('Squash Court', '2012-08', 184)
('Squash Court', '2012-09', 184)
('Snooker Table', '2012-07', 140)
('Snooker Table', '2012-08', 316)
('Snooker Table', '2012-09', 404)
('Pool Table', '2012-07', 110)
('Pool Table', '2012-08', 303)
('Pool Table', '2012-09', 443)